# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   namespace: argocd
#   name: argo-cd-ui
#   annotations:
#     nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
#     nginx.ingress.kubernetes.io/ssl-passthrough: "true"
# spec:
#   ingressClassName: nginx
#   rules:
#   - host: director.prossertech.com
#     http:
#       paths:
#       - pathType: Prefix
#         path: /argocd
#         backend:
#           service:
#             name: argo-cd-argocd-server
#             port: 
#               name: http 
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-server-http-ingress
  namespace: argocd
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: argo-cd-argocd-server
            port:
              name: http
    host: argocd-internal.int.prossertech.com
  tls:
  - hosts:
    - "*.int.prossertech.com"
    secretName: int-prossertech-com